# Public Specs Repository:
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '11.0'

def local_pods_path
    { :path => '../../../' }
end

target 'IntgrateGAM_Example' do
  pod 'IntgrateGAM', local_pods_path

end

target 'IntgrateGAM_Tests' do
    inherit! :search_paths

end

